### ISSUE TITLE
Modyfikacja Qustion

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/FakeCheck#11]
model question musi mieć jeszcze jedno pole - title. Czyli nieduże pole, które będize zawierało główną istotę problemu, coś jak tytuł w poście na blogu. Znowu podobny mechanizm jest na reddicie - każdy wpis ma tytuł i jego większa treść pojawia się dopiero po kliknięciu w ten tytuł

**Comment by dwdzdc** [comment]
Musi tu być ogarniczenie znakowe - zakładamy ok 180 znaków?

**Comment by Szczepaniak-M** [comment]
Wezmę się za to
