### ISSUE TITLE
Widok pytania dla eksperta

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/FakeCheck#15]
Ekspert po wejściu w pytanie powinien zobaczyć tytuł pytania, treść pytania i źródła (to znaczy jeżeli jakieś są a powinny być dodane do pytania). Powinien również mieć przycisk recenzuj który będzie go przekierowywał na formularz z issue #14

**Comment by dwdzdc** [comment]
Każdy powinien mieć możliwość podglądu pytania do eksperta ale użytkownicy frontowi tylko pod warunkiem, że liczba recenzji to więcej niż X. 

Dodatkowo pod pytaniem powinny pojawić się linki do poszczególnych recenzji powiązanych z pytaniem. Przykładowo: profesor Janusz Kawanaławę napisał recenzję na temat newsa, a więc pod newsem wyświetlamy link - "Opinia: prof Janusz Kawanaławę" (Opinia bo dla szerszej publiczności nie chcemy używać słowa "recenzja" - to tylko slang domenowy).

**Comment by Cheriit** [comment]
Osobiście połączyłbym widok pytania i recenzji, co przyspieszyłoby pracę

**Comment by Cheriit** [comment]
Dodać linkowanie do tagów
