### ISSUE TITLE
WIdok recenzji eksperta

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/FakeCheck#17]
Recenzja eksperta powinna być widoczna pod pytaniem i powinna być dostępna dla każdego kto może zobaczyć pytanie. 

Jeżeli recenzja została napisana przez eksperta który właśnie na nią patrzy, to powinien on mieć dodatkowo przycisk lub formularz "zgłoś zmianę", który sprawi że ekspert będzie mógł opisać potrzebę zmiany recenzji. Taka prośba idzie na maila administratora razem z linkiem do pytania i recenzji której dotyczy, a ten z kolei ma za zadanie zdecydować czy zmianę należy zastosować i ewentualnie zadać dalsze pytania zgłaszającemu.

**Comment by Cheriit** [comment]
Czy musi być możliwość zgłoszenia zmiany? Sądzę, że wygodniej byłoby, jakby ekspert był w stanie edytować swoją odpowiedź "na zwołanie"
