### ISSUE TITLE
Tworzenie experta w panelu admina 

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/FakeCheck#22]
Tworzenie experta odbywac sie bedzie przez panel admina, a tam musimy tworzyc dwa modoele - experta i usera. Dane do tego pierwszego sa juz predefiniowane w formularzu, natomiast dane do tego drugiego nalezy dopiero umiescic w tym formularzu: to znaczy chcemy tam miec rowniez mozliwosc nadania imienia, nazwiska, maila (moze to sie nawet odbywac w tym popupie co wyskakuje po kliknieciu plusa obok listy userów)

**Comment by Szczepaniak-M** [comment]
Od razu ogarnę cały ten panel admina by jakoś normalnie wyglądał
