### ISSUE TITLE
Redaktor - lista moich pytań

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/FakeCheck#9]
Redaktor powinien mieć dostęp do listy pytań które sam stworzył. Razem z tą listą powinien mieć możliwość pełnego ich wyświetlenia i edycji oraz usuwania.

**Comment by Szczepaniak-M** [comment]
Obecnie lista po stworzeniu nie jest wiązana z żadnym redaktorem, wiec trzeba to będzie zmienić w modelu

**Comment by Szczepaniak-M** [comment]
Okej, już model jest poprawny
